package com.example.starwarscharactersapp.domain.model

data class StarWarsCharacter(
    val id: String = "",
    val birthYear: String = "",
    val eyeColor: String = "",
    val filmUrls: List<String> = emptyList(),
    val films: List<Film> = emptyList(),
    val filmsError: String? = null,
    val gender: String = "",
    val hairColor: String = "",
    val height: String = "",
    val homeworld: String = "",
    val planet: Planet? = null,
    val planetError: String? = null,
    val mass: String = "",
    val name: String = "",
    val skinColor: String = "",
    val starshipUrls: List<String> = emptyList(),
    val starships: List<Starship> = emptyList(),
    val starshipsError: String? = null,
    val vehicleUrls: List<String> = emptyList(),
    val vehicles: List<Vehicle> = emptyList(),
    val vehiclesError: String? = null,
    val url: String = "",
    val imageUrl: String? = null,
    val imageError: String? = null,
    val imageRetryKey: Int = 0,
    val description: String = "",
    val isFavorite: Boolean = false,
)